"""v2 subscription digest notification wiki knowledge tables

Revision ID: 06ce59b1c673
Revises: 950f69ee2ca9
Create Date: 2026-09-13 00:31:16.098587

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "06ce59b1c673"
down_revision: str | None = "950f69ee2ca9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_setting_history",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notification_setting_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_setting_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_setting_history_key"), ["key"], unique=False
        )

    op.create_table(
        "notification_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending_confirmation",
                "confirmed",
                "unsubscribed",
                name="subscriptionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum("daily", "weekly", name="subscriptionfrequency", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("max_items", sa.Integer(), nullable=False),
        sa.Column("confirm_token_hash", sa.String(length=64), nullable=False),
        sa.Column("confirm_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unsubscribe_token_hash", sa.String(length=64), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscriptions_confirm_token_hash"), ["confirm_token_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_subscriptions_email"), ["email"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_subscriptions_unsubscribe_token_hash"),
            ["unsubscribe_token_hash"],
            unique=True,
        )

    op.create_table(
        "wiki_entries",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "retired", "merged", name="wikientrystatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "created_by",
            sa.Enum("llm", "human", name="wikientrysourcetype", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("merged_into_id", sa.String(length=64), nullable=True),
        sa.Column("human_note", sa.Text(), nullable=True),
        sa.Column("embedding", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["wiki_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("wiki_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wiki_entries_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_wiki_entries_status"), ["status"], unique=False)

    op.create_table(
        "digests",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("subscription_id", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "sent",
                "failed",
                "skipped_empty",
                name="digeststatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("item_count", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subscription_id", "period_start", "period_end"),
    )
    with op.batch_alter_table("digests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_digests_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_digests_subscription_id"), ["subscription_id"], unique=False
        )

    op.create_table(
        "subscription_topics",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("subscription_id", sa.String(length=64), nullable=False),
        sa.Column(
            "topic_type",
            sa.Enum(
                "category",
                "tag",
                "source",
                "keyword",
                name="subscriptiontopictype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("topic_value", sa.String(length=300), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("subscription_id", "topic_type", "topic_value"),
    )
    with op.batch_alter_table("subscription_topics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscription_topics_subscription_id"), ["subscription_id"], unique=False
        )

    op.create_table(
        "digest_items",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("digest_id", sa.String(length=64), nullable=False),
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("matched_topics", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["digest_id"], ["digests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("digest_id", "article_id"),
    )
    with op.batch_alter_table("digest_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_digest_items_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_digest_items_digest_id"), ["digest_id"], unique=False)

    op.create_table(
        "knowledge_decisions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column(
            "decision",
            sa.Enum(
                "new_knowledge",
                "partial",
                "covered",
                "pending",
                name="knowledgedecisiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("matched_entry_id", sa.String(length=64), nullable=True),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("points", sa.JSON(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt_version", sa.String(length=120), nullable=True),
        sa.Column(
            "actor",
            sa.Enum("system", "human", name="decisionactor", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["matched_entry_id"],
            ["wiki_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("knowledge_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_knowledge_decisions_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_decisions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_knowledge_decisions_decision"), ["decision"], unique=False
        )

    op.create_table(
        "wiki_entry_sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("entry_id", sa.String(length=64), nullable=False),
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entry_id"], ["wiki_entries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("entry_id", "article_id"),
    )
    with op.batch_alter_table("wiki_entry_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_wiki_entry_sources_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_wiki_entry_sources_entry_id"), ["entry_id"], unique=False
        )

    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "knowledge_status",
                sa.Enum(
                    "new",
                    "partial",
                    "covered",
                    "pending",
                    name="knowledgestatus",
                    native_enum=False,
                    length=32,
                ),
                nullable=True,
            )
        )
        batch_op.create_index(
            batch_op.f("ix_articles_knowledge_status"), ["knowledge_status"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_articles_knowledge_status"))
        batch_op.drop_column("knowledge_status")

    with op.batch_alter_table("wiki_entry_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wiki_entry_sources_entry_id"))
        batch_op.drop_index(batch_op.f("ix_wiki_entry_sources_article_id"))

    op.drop_table("wiki_entry_sources")
    with op.batch_alter_table("knowledge_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_knowledge_decisions_decision"))
        batch_op.drop_index(batch_op.f("ix_knowledge_decisions_created_at"))
        batch_op.drop_index(batch_op.f("ix_knowledge_decisions_article_id"))

    op.drop_table("knowledge_decisions")
    with op.batch_alter_table("digest_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_digest_items_digest_id"))
        batch_op.drop_index(batch_op.f("ix_digest_items_article_id"))

    op.drop_table("digest_items")
    with op.batch_alter_table("subscription_topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscription_topics_subscription_id"))

    op.drop_table("subscription_topics")
    with op.batch_alter_table("digests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_digests_subscription_id"))
        batch_op.drop_index(batch_op.f("ix_digests_status"))

    op.drop_table("digests")
    with op.batch_alter_table("wiki_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_wiki_entries_status"))
        batch_op.drop_index(batch_op.f("ix_wiki_entries_name"))

    op.drop_table("wiki_entries")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_unsubscribe_token_hash"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_email"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_confirm_token_hash"))

    op.drop_table("subscriptions")
    op.drop_table("notification_settings")
    with op.batch_alter_table("notification_setting_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_setting_history_key"))
        batch_op.drop_index(batch_op.f("ix_notification_setting_history_created_at"))

    op.drop_table("notification_setting_history")
    # ### end Alembic commands ###
