"""add crawl_pages

Revision ID: 11c59f322d36
Revises: a58834147d87
Create Date: 2026-09-11 15:40:28.402455

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "11c59f322d36"
down_revision: str | None = "a58834147d87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crawl_pages",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("raw_html", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "fetched",
                "failed",
                "robots_denied",
                "skipped",
                name="crawlstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "url", name="uq_crawl_page_source_url"),
    )
    with op.batch_alter_table("crawl_pages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crawl_pages_source_id"), ["source_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_crawl_pages_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_crawl_pages_status_fetched", ["status", "fetched_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crawl_pages", schema=None) as batch_op:
        batch_op.drop_index("ix_crawl_pages_status_fetched")
        batch_op.drop_index(batch_op.f("ix_crawl_pages_status"))
        batch_op.drop_index(batch_op.f("ix_crawl_pages_source_id"))

    op.drop_table("crawl_pages")
    # ### end Alembic commands ###
