"""add dedup_setting_history

Revision ID: 950f69ee2ca9
Revises: f451779aadc2
Create Date: 2026-09-11 15:53:50.900415

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "950f69ee2ca9"
down_revision: str | None = "f451779aadc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedup_setting_history",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("old_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dedup_setting_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dedup_setting_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_dedup_setting_history_key"), ["key"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedup_setting_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dedup_setting_history_key"))
        batch_op.drop_index(batch_op.f("ix_dedup_setting_history_created_at"))

    op.drop_table("dedup_setting_history")
    # ### end Alembic commands ###
