"""initial core schema

Revision ID: a58834147d87
Revises:
Create Date: 2026-09-11 15:36:27.974935

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "a58834147d87"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="categorystatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("site_url", sa.String(length=1000), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("focus_area_name", sa.String(length=200), nullable=True),
        sa.Column("focus_area_description", sa.Text(), nullable=True),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("exclude_keywords", sa.JSON(), nullable=False),
        sa.Column("example_urls", sa.JSON(), nullable=False),
        sa.Column("counter_example_urls", sa.JSON(), nullable=False),
        sa.Column(
            "list_type",
            sa.Enum(
                "whitelist",
                "blacklist",
                "neutral",
                name="sourcelisttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column(
            "update_frequency",
            sa.Enum(
                "high",
                "normal",
                "low",
                "custom",
                name="updatefrequency",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("update_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_url"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index("ix_sources_list_type", ["list_type"], unique=False)

    op.create_table(
        "tags",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "articles",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("primary_category_id", sa.String(length=64), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "normal",
                "uncategorized",
                "error",
                "filtered",
                name="articlestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("is_accessible", sa.Boolean(), nullable=False),
        sa.Column("accessibility_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["primary_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_articles_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_articles_primary_category_id"), ["primary_category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_articles_simhash"), ["simhash"], unique=False)
        batch_op.create_index(batch_op.f("ix_articles_source_id"), ["source_id"], unique=False)
        batch_op.create_index(
            "ix_articles_source_published", ["source_id", "published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_articles_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_articles_status_published", ["status", "published_at"], unique=False
        )

    op.create_table(
        "category_history",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("category_id", sa.String(length=64), nullable=True),
        sa.Column(
            "action",
            sa.Enum(
                "create",
                "rename",
                "merge",
                "deactivate",
                "activate",
                name="categoryaction",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("old_name", sa.String(length=200), nullable=True),
        sa.Column("new_name", sa.String(length=200), nullable=True),
        sa.Column("target_category_id", sa.String(length=64), nullable=True),
        sa.Column("actor", sa.String(length=200), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["target_category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_category_history_category_id"), ["category_id"], unique=False
        )

    op.create_table(
        "article_tags",
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column("tag_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("article_id", "tag_id"),
    )
    op.create_table(
        "duplicate_relations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("group_key", sa.String(length=64), nullable=True),
        sa.Column(
            "relation_type",
            sa.Enum(
                "exact_duplicate",
                "near_duplicate",
                "related",
                name="deduprelationtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("article_id", sa.String(length=64), nullable=False),
        sa.Column("target_article_id", sa.String(length=64), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_article_id"], ["articles.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "article_id", "target_article_id", "relation_type", name="uq_duplicate_relation"
        ),
    )
    with op.batch_alter_table("duplicate_relations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_duplicate_relations_article_id"), ["article_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_duplicate_relations_group_key"), ["group_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_duplicate_relations_relation_type"), ["relation_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_duplicate_relations_target_article_id"),
            ["target_article_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("duplicate_relations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_duplicate_relations_target_article_id"))
        batch_op.drop_index(batch_op.f("ix_duplicate_relations_relation_type"))
        batch_op.drop_index(batch_op.f("ix_duplicate_relations_group_key"))
        batch_op.drop_index(batch_op.f("ix_duplicate_relations_article_id"))

    op.drop_table("duplicate_relations")
    op.drop_table("article_tags")
    with op.batch_alter_table("category_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_category_history_category_id"))

    op.drop_table("category_history")
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index("ix_articles_status_published")
        batch_op.drop_index(batch_op.f("ix_articles_status"))
        batch_op.drop_index("ix_articles_source_published")
        batch_op.drop_index(batch_op.f("ix_articles_source_id"))
        batch_op.drop_index(batch_op.f("ix_articles_simhash"))
        batch_op.drop_index(batch_op.f("ix_articles_primary_category_id"))
        batch_op.drop_index(batch_op.f("ix_articles_content_hash"))

    op.drop_table("articles")
    op.drop_table("tags")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index("ix_sources_list_type")

    op.drop_table("sources")
    op.drop_table("categories")
    # ### end Alembic commands ###
