"""add dedup_settings

Revision ID: f451779aadc2
Revises: 11c59f322d36
Create Date: 2026-09-11 15:49:47.446555

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "f451779aadc2"
down_revision: str | None = "11c59f322d36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedup_settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.String(length=255), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dedup_settings")
    # ### end Alembic commands ###
